/**
 * Copyright by Ruman Gerst
 * Research Group Applied Systems Biology - Head: Prof. Dr. Marc Thilo Figge
 * https://www.leibniz-hki.de/en/applied-systems-biology.html
 * HKI-Center for Systems Biology of Infection
 * Leibniz Institute for Natural Product Research and Infection Biology - Hans Knöll Insitute (HKI)
 * Adolf-Reichwein-Straße 23, 07745 Jena, Germany
 *
 * This code is licensed under BSD 2-Clause
 * See the LICENSE file provided with this code for the full license.
 */

#pragma once
#include <misaxx/core/misa_task.h>

namespace misaxx_analyzer {

    /**
     * The serialization schemata generated by the framework might be incomplete (e.g. they do not include children)
     * This task traverses the serialization schemata and builds a new file that contains all data types
     */
    struct schema_traversion_task : public misaxx::misa_task {

        using misaxx::misa_task::misa_task;

        void work() override;

        void create_parameters(misaxx::misa_parameter_builder &t_parameters) override;
    };
}

